// DEPRECATED — this file is NOT deployed and should be deleted.
//
// The real worker entry point is: backend/worker/src/index.js
// (see wrangler.toml: main = "backend/worker/src/index.js")
//
// This monolithic file was the original prototype. All logic has been
// migrated to the modular src/ structure. Do not edit this file.
// Delete it once you can — it only exists because the sandbox can't remove it.
throw new Error('This file is not the deployed worker. See backend/worker/src/index.js')
